const texts = [
    "Saya suka makan kereta biru!",
    "Ini adalah contoh lain.",
    "Hari ini cuaca sangat cerah.",
    "Saya ingin pergi ke pantai.",
    "Apakah kamu sudah makan?",
    "Apa rencanamu untuk liburan?",
    "Saya sedang belajar bahasa JavaScript.",
    "Pohon-pohon di taman sangat indah.",
    "Tolong berikan saya secangkir kopi.",
    "Buku ini sangat menarik untuk dibaca.",
    "Kucing saya suka bermain dengan bola benang.",
    "Kamu tahu bermain gitar?",
    "Aku ingin pergi ke bioskop.",
    "Mobil itu berwarna merah.",
    "Dia adalah teman saya sejak kecil.",
    "Kamu sudah pernah ke luar negeri?",
    "Hari ini saya merasa sangat lelah.",
    "Apa kabar teman-teman sekolahmu?",
    "Saya ingin belajar memasak.",
    "Pesta ulang tahunnya akan diadakan besok.",
    "Pulau itu terkenal dengan keindahan alamnya.",
    "Apa hobi favoritmu?",
    "Saya suka mendengarkan musik.",
    "Kamu suka menonton film?",
    "Baju ini terlalu kecil bagiku.",
    "Aku sangat senang bisa bertemu denganmu.",
    "Apakah kamu ingin ikut ke pesta malam ini?",
    "Hari ini saya memiliki banyak pekerjaan yang harus diselesaikan.",
    "Saya ingin memiliki rumah di tepi pantai.",
    "Mereka sedang menonton pertunjukan teater.",
    "Pertandingan sepak bola itu sangat seru.",
    "Apakah kamu suka bermain game?",
    "Saya sedang mencari pekerjaan yang baru.",
    "Mobil itu berjalan dengan kecepatan tinggi.",
    "Kamu ingin pergi ke taman bersamaku?",
    "Saya ingin membeli hadiah untuk ibu saya.",
    "Dia adalah guru terbaik yang pernah saya miliki.",
    "Kota ini memiliki banyak tempat wisata yang menarik.",
    "Apakah kamu suka berenang?",
    "Saya ingin menjadi seorang penulis sukses.",
    "Saya akan pergi ke pasar untuk membeli beberapa buah.",
    "Apa makanan favoritmu?",
    "Kami akan pergi ke pantai pada akhir pekan.",
    "Saya ingin mencoba hal baru.",
    "Tolong beri tahu saya alamat rumahmu.",
    "Dia adalah aktor terkenal di negara ini.",
    "Kamu tahu cara memasak spaghetti?",
    "Saya senang melihat bunga-bunga yang mekar.",
    "Kamu sudah melihat film terbaru itu?",
    "Buku ini memiliki cerita yang menginspirasi.",
    "Aku sedang menunggu tugas ini selesai.",
    "Hari ini adalah hari yang istimewa.",
    "Saya ingin pergi ke konser musik.",
    "Pakaianmu terlihat sangat bagus.",
    "Apakah kamu suka bermain olahraga?",
    "Saya ingin pergi ke luar kota bersama keluarga.",
    "Kamu tahu cara membuat kue brownies?",
    "Aku ingin menjadi seorang penulis terkenal.",
    "Mobil itu terlihat sangat mahal.",
    "Dia adalah teman sekelas saya.",
    "Kamu sudah menyelesaikan tugas sekolahmu?",
    "Apa hewan peliharaan favoritmu?",
    "Saya ingin mencoba makanan baru.",
    "Buku ini memiliki ilustrasi yang indah.",
    "Aku sedang menantikan liburan musim panas.",
    "Kamu suka mendengarkan podcast?",
    "Saya ingin bermain musik di sebuah band.",
    "Kamu tahu cara menari tarian tradisional ini?",
    "Saya sangat senang bisa menghadiri pesta itu.",
    "Hari ini saya merayakan ulang tahun.",
    "Apa impian terbesarmu?",
    "Saya ingin pergi ke taman hiburan.",
    "Kamu suka naik sepeda?",
    "Baju ini sangat cocok bagimu.",
    "Aku ingin mempelajari bahasa asing.",
    "Apakah kamu sudah pernah ke museum ini?",
    "Saya ingin belajar bermain piano.",
    "Mobil itu terparkir di depan rumah.",
    "Dia adalah teman baik saya.",
    "Kamu suka mendaki gunung?",
    "Saya sedang mencari pekerjaan paruh waktu.",
    "Saya ingin pergi ke konser musik rock.",
    "Kamu sudah mencoba makanan khas daerah ini?",
    "Aku sedang menunggu panggilan telepon dari teman saya.",
    "Hari ini cuaca sangat panas.",
    "Apa hobi terbaru yang kamu coba?",
    "Saya ingin memiliki kucing peliharaan.",
    "Buku ini memberikan banyak pengetahuan baru.",
    "Kamu sudah membaca novel terbaru itu?",
    "Aku sangat berharap bisa lulus ujian ini.",
    "Saya ingin bermain sepak bola di tim lokal.",
    "Kamu tahu cara menggambar?",
    "Saya senang melihat seni rupa.",
    "Kamu sudah mencoba restoran baru ini?",
    "Apa film favoritmu?",
    "Saya ingin melakukan perjalanan ke luar negeri.",
    "Saya akan berangkat kerja lebih awal hari ini.",
    "Apakah kamu suka menulis cerita pendek?",
    "Saya ingin pergi ke pesta pernikahan teman saya.",
    "Kamu sudah belajar bahasa asing sebelumnya?",
    "Aku sedang menunggu pesan dari seseorang.",
    "Hari ini saya merasa sangat bahagia.",
    "Apa acara TV favoritmu?",
    "Saya ingin belajar memainkan alat musik baru.",
    "Kamu suka bermain tenis?",
    "Baju ini terlalu besar bagiku.",
    "Aku ingin mencoba makanan khas daerah ini.",
    "Mobil itu berhenti di lampu merah.",
    "Dia adalah rekan kerja saya.",
    "Kamu sudah mencoba olahraga baru ini?",
    "Saya ingin pergi ke pesta ulang tahun teman saya.",
    "Apakah kamu suka bersepeda?",
    "Saya ingin belajar menggambar manga.",
    "Pantai itu sangat indah pada saat matahari terbenam.",
    "Kamu sudah menonton konser musik live?",
    "Buku ini mengajarkan banyak hal baru.",
    "Aku sedang menulis cerita pendek.",
    "Hari ini cuaca sangat mendung.",
    "Apa hewan peliharaan yang ingin kamu miliki?",
    "Saya ingin pergi ke festival musik.",
    "Kamu sudah mencoba kegiatan baru ini?",
    "Aku sedang menunggu pesawat di bandara.",
    "Saya senang melihat pemandangan di pegunungan.",
    "Kamu suka menonton pertunjukan teater?",
    "Baju ini memiliki warna yang cerah.",
    "Aku ingin memiliki anjing peliharaan.",
    "Saya ingin bermain bulu tangkis di klub lokal.",
    "Kamu tahu bermain piano?",
    "Saya sedang membaca buku novel terbaru.",
    "Kamu sudah mencoba olahraga air ini?",
    "Apa film terakhir yang kamu tonton?",
    "Saya ingin mencoba makanan khas daerah lain.",
    "Aku sedang menulis puisi.",
    "Hari ini cuaca sangat dingin.",
    "Apakah kamu suka menonton pertandingan sepak bola?",
    "Saya ingin pergi ke pesta pernikahan saudara saya.",
    "Kamu suka bermain basket?",
    "Saya ingin belajar memasak masakan Italia.",
    "Pakaianmu terlihat sangat keren.",
    "Aku ingin mencoba olahraga ekstrem ini.",
    "Mobil itu terlihat sangat keren.",
    "Dia adalah sahabat baik saya.",
    "Kamu sudah mencoba olahraga selam ini?",
    "Saya ingin pergi ke pesta malam di kota ini.",
    "Apakah kamu suka bermain golf?",
    "Saya ingin belajar menari tarian tradisional.",
    "Kamu tahu cara memasak hidangan khas ini?",
    "Saya sedang menonton film terbaru.",
    "Kamu suka menggambar?",
    "Aku ingin memiliki kura-kura peliharaan.",
    "Saya ingin bermain tenis di lapangan umum.",
    "Buku ini memiliki sampul yang menarik.",
    "Aku sedang menonton serial TV baru.",
    "Hari ini adalah hari yang istimewa untukku.",
    "Apa acara TV terbaru yang kamu ikuti?",
    "Saya ingin belajar menari balet.",
    "Kamu suka bermain golf?",
    "Baju ini terlalu panjang bagiku.",
    "Aku ingin mencoba olahraga angkat berat.",
    "Mobil itu berhenti di depan toko.",
    "Dia adalah teman dekat saya sejak kecil.",
    "Kamu sudah mencoba olahraga panjat tebing ini?",
    "Saya ingin pergi ke pesta malam dengan teman-teman.",
    "Apakah kamu suka bermain tenis meja?",
    "Saya ingin belajar bermain alat musik tradisional.",
    "Kamu tahu cara membuat sushi?",
    "Saya sedang menonton serial TV favorit.",
    "Kamu suka menulis puisi?",
    "Aku ingin memiliki burung peliharaan.",
    "Saya ingin bermain voli di pantai.",
    "Buku ini memiliki cerita yang menghibur.",
    "Aku sedang menunggu bus di halte.",
    "Hari ini cuaca sangat sejuk.",
    "Apa makanan terakhir yang kamu coba?",
    "Saya ingin pergi ke konser musik klasik.",
    "Kamu suka bermain badminton?",
    "Saya ingin belajar memasak masakan Thailand.",
    "Pakaianmu terlihat sangat modis.",
    "Aku ingin mencoba olahraga panahan.",
    "Mobil itu terlihat sangat elegan.",
    "Dia adalah teman sekerja saya.",
    "Kamu sudah mencoba olahraga renang ini?",
    "Saya ingin pergi ke pesta ulang tahun keponakan saya.",
    "Apakah kamu suka bermain hoki?",
    "Saya ingin belajar menari salsa.",
    "Kamu tahu cara membuat kue tart?",
    "Saya sedang menonton film dokumenter.",
    "Kamu suka menggambar manga?",
    "Aku ingin memiliki kelinci peliharaan.",
    "Saya ingin bermain bulu tangkis di klub lokal.",
    "Buku ini memberikan banyak inspirasi.",
    "Aku sedang menonton acara TV realitas.",
    "Hari ini adalah hari yang istimewa untuk kita semua.",
    "Apa acara TV terakhir yang kamu tonton?",
    "Saya ingin belajar menari hip hop.",
    "Kamu suka bermain tenis meja?",
    "Saya ingin mencoba olahraga ski air.",
    "Kamu tahu cara membuat makanan penutup ini?",
    "Saya sedang menonton film komedi.",
    "Kamu suka menulis cerita fiksi?",
    "Aku ingin memiliki hamster peliharaan.",
    "Saya ingin bermain sepak bola di lapangan terbuka.",
    "Buku ini memiliki gambar yang mengagumkan.",
    "Aku sedang menunggu pesawat di bandara internasional.",
    "Hari ini cuaca sangat panas sekali.",
    "Apakah kamu suka menonton pertandingan basket?",
    "Saya ingin pergi ke pesta pernikahan teman baik saya.",
    "Kamu suka bermain bulu tangkis?",
    "Saya ingin belajar memasak hidangan India.",
    "Pakaianmu terlihat sangat elegan.",
    "Aku ingin mencoba olahraga berselancar.",
    "Mobil itu berjalan di jalan yang ramai.",
    "Dia adalah teman kuliah saya.",
    "Kamu sudah mencoba olahraga arung jeram ini?",
    "Saya ingin pergi ke pesta malam bersama teman-teman.",
    "Apakah kamu suka bermain baseball?",
    "Saya ingin belajar menari tango.",
    "Kamu tahu cara membuat makanan penutup khas ini?",
    "Saya sedang menonton film horor.",
    "Kamu suka menggambar karakter anime?",
    "Aku ingin memiliki ikan peliharaan.",
    "Saya ingin bermain bola basket di lapangan terbuka.",
    "Buku ini memberikan banyak wawasan baru.",
    "Aku sedang menonton acara TV drama.",
    "Hari ini adalah hari yang spesial bagiku.",
    "Apa acara TV favorit terbaru yang kamu ikuti?",
    "Saya ingin belajar menari flamenco.",
    "Kamu suka bermain tenis lapangan?",
    "Saya ingin mencoba olahraga bulu tangkis ganda.",
    "Kamu tahu cara membuat kue donat?",
    "Saya sedang menonton film aksi.",
    "Kamu suka menulis cerita horor?",
    "Aku ingin memiliki ular peliharaan.",
    "Saya ingin bermain bola voli di pantai.",
    "Buku ini memiliki ilustrasi yang menakjubkan.",
    "Aku sedang menunggu kereta di stasiun.",
    "Hari ini cuaca sangat cerah sekali.",
    "Apakah kamu suka menonton pertandingan hoki?",
    "Saya ingin pergi ke pesta ulang tahun keponakan perempuan saya.",
    "Kamu suka bermain sepak takraw?",
    "Saya ingin belajar memasak hidangan Jepang.",
    "Pakaianmu terlihat sangat trendi.",
    "Aku ingin mencoba olahraga terjun payung.",
    "Mobil itu berjalan di jalan yang sepi.",
    "Dia adalah teman kantor saya.",
    "Kamu sudah mencoba olahraga bulu tangkis tunggal ini?",
    "Saya ingin pergi ke pesta pernikahan sahabat baik saya.",
    "Apakah kamu suka bermain bola voli?",
    "Saya ingin belajar menari breakdance.",
    "Kamu tahu cara membuat makanan penutup tradisional ini?",
    "Saya sedang menonton film romantis.",
    "Kamu suka menggambar pemandangan alam?",
    "Aku ingin memiliki kucing peliharaan.",
    "Saya ingin bermain bola basket di lapangan indoor.",
    "Buku ini memberikan banyak ide kreatif.",
    "Aku sedang menonton acara TV komedi.",
    "Hari ini adalah hari yang luar biasa.",
    "Apa acara TV terakhir yang kamu tonton dengan keluarga?",
    "Saya ingin belajar menari belly dance.",
    "Kamu suka bermain tenis lapangan?",
    "Saya ingin mencoba olahraga bulu tangkis tunggal putri.",
    "Kamu tahu cara membuat makanan ringan ini?",
    "Saya sedang menonton film animasi.",
    "Kamu suka menulis cerita petualangan?",
    "Aku ingin memiliki hamster peliharaan.",
    "Saya ingin bermain sepak takraw di pantai.",
    "Buku ini memiliki ilustrasi yang menginspirasi.",
    "Aku sedang menunggu taksi di pinggir jalan.",
    "Hari ini cuaca sangat sejuk sekali.",
    "Apakah kamu suka menonton pertandingan baseball?",
    "Saya ingin pergi ke pesta pernikahan saudara perempuan saya.",
    "Kamu suka bermain sepak takraw?",
    "Saya ingin belajar memasak hidangan Korea.",
    "Pakaianmu terlihat sangat stylish."
]
  